name: chopin2
owner: fabio
categories:
  - Machine Learning
description: chopin2
long_description: |
  Domain-Agnostic Supervised Learning with Hyperdimensional Computing
remote_repository_url: https://github.com/fabio-cumbo/chopin2
homepage_url: https://github.com/fabio-cumbo/chopin2
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  descriptor_template: "Galaxy wrapper for {{ tool_name }}"
